version: '3'

services:
    texlive:
      build:
        context: .
        dockerfile: ./docker/texlive/Dockerfile
      volumes:
        - ./app:/workdir
      restart: always
      working_dir: /workdir/src
      command: sh -c "latexmk -pvc main.tex"
    textlint:
      build:
        context: .
        dockerfile: ./docker/textlint/Dockerfile
      volumes: 
        - ./app/src:/src
      tty: true

