name: Lint

on: 
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - name: Build the Docker image
        run: docker-compose build textlint
      - name: lint
        run: docker-compose run --rm textlint npm run --silent textlint-check
