name: Lint & Release

on: 
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker-compose build textlint
      - name: Lint
        run: docker-compose run --rm textlint npm run --silent textlint-check
      - name: Release
        uses: MaineK00n/latex-actions@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: MaineK00n/docker-paper
          pdf_name: docker-paper